### PR TITLE
Feature/floor polygon

### PR DESCRIPTION
**Pull request by ooms97**
Added feature to display floor plans using google maps polygons. The floor selector also changes the polygon based on the selected floor.

### CODE REVIEW

**Comment by DiveshPatel** [comment]
Will require refactor once database has been setup

**Comment by ooms97** [comment]
Closing PR temporarily as features are still being implemented.

**Comment by ooms97** [comment]
> * I'm really not a fan of the waypoint icon markers showing up like that, and I would not include that in this PR
> * I think the bottom left "go inside" button that was made for SVGs is not a desirable functionality for floor polygon's, and should be removed
> 
> I like the implementation of the main goal of this PR which is the floor polygons. If you can make this PR only about that, I would give my approval to merge those changes immediately.
> 
> I'm not saying to completely scrap the work that was done for the waypoints, but I suggest we keep that work in another working branch so that we can go back to the drawing board to find a possibly better implementation because it honestly looks horrible... :/ I'll leave it to the others to approve including the points I do not like if this is truly the direction we want to take going forward, else I personally think that those negative points I brought up need more work before merging to master

For your first point, I agree the markers look weird so we're working on making custom markers that are smaller, and ideally markers with labels for room number so it is visually easy to identify classrooms. The label issue is difficult to solve on Flutter, but it should be possible.

As for your second point, we've removed the go inside button to simply put a floor selector.

There is still some work being done on this PR, so feel free to keep leaving feedback on the progress so we can continually make this look better.

**Comment by ooms97** [comment]
@MrJCipherButtles please take a look at the new code.

**Pull request merged**
