### PR TITLE
Created building helper class.

### PR DESCRIPTION
**Pull request by ooms97**
Added helper class as singleton to easily retrieve building floors and rooms.

### CODE REVIEW

**Comment by MrJCipherButtles** [comment]
@ooms97 You might want to do something about the code coverage failed check. It seems like this class is influencing the code coverage quite substantially even though it has little complexity

**Comment by ooms97** [comment]
> @ooms97 You might want to do something about the code coverage failed check. It seems like this additions are influencing the code coverage quite substantially even though it has little complexity

I will take a look at fixing the code coverage before merging, thanks for the heads up!

**Comment by MrJCipherButtles** [comment]
Also you might want to link this PR to US-5 and US-23 unless the plan is to do so when we push the widget update PR? Also it may be more fitting to move your data singleton from /models to a new /data directory?

**Comment by ooms97** [comment]
> Also you might want to link this PR to US-5 and US-23 unless the plan is to do so when we push the widget update PR?

There will be seperate PRs targeting those user stories specifically. As for the file location, I will change that.

**Comment by ooms97** [comment]
Fixed the codecov patch, thanks @ChesterLY for the help!

**Pull request merged**
