### PR TITLE
Feature/Indoor-Directions

### PR DESCRIPTION
**Pull request by ooms97**
This PR is to fix the indoor directions and create start/end icons.

### CODE REVIEW

**Comment by ooms97** [comment]
There's an issue when moving the map while on 8th floor, will fix this soon.

**Comment by MrJCipherButtles** [comment]
I did adjustments to the zoom settings and there was an svg function that was related to moving the camera position in the code that was not necessary, so, I deleted those lines

**Comment by MrJCipherButtles** [comment]
> There's an issue when moving the map while on 8th floor, will fix this soon.

@ooms97 I'll submit my review when you submit your fix, but all looks good other than a few quirks, but nothing worrisome from what I see and tested 👍

**Comment by ooms97** [comment]
> > There's an issue when moving the map while on 8th floor, will fix this soon.
> 
> @ooms97 I'll submit my review when you submit your fix unless my changes did it for you? But all looks good other than a few quirks, but nothing worrisome from what I see and tested 👍

@MrJCipherButtles Yup, looks like your changes fixed it, thanks :)

**Pull request merged**
