### PR TITLE
refactored test file structure to match lib, removed plurals, and fix…

### PR DESCRIPTION
**Pull request by MrJCipherButtles**
…ed imports

No code was changed nor added, I just moved things around to fit a certain standard. What do you think about mirroring the test file structure to the lib file structure? Also we should follow conventions on not pluralizing names. If most approve this structure, I will merge this into master.

### CODE REVIEW

**Comment by MrJCipherButtles** [comment]
> I think that unit tests and widget tests should be separated into their own directories.

Can you elaborate? the test directory is a required standard for the build. Are you saying you would want unit and widget directories under test, and then mirror the structure of lib under both unit and widget directories?

**Comment by ooms97** [comment]
> > I think that unit tests and widget tests should be separated into their own directories.
> 
> @ooms97 Can you elaborate? the test directory is a required standard for the build. Are you saying you would want unit and widget directories under test, and then mirror the structure of lib under both unit and widget directories? I don't mind adding an extra level to do the distinction, if that is what you are asking

@MrJCipherButtles Yes, that's what I mean. We can mirror the src structure but also add a unit_test and widget_test directory. For example, the class in /lib/model/building.dart would have an associated unit test in /test/unit_test/lib/model/building_test.dart

**Comment by MrJCipherButtles** [comment]
> > > I think that unit tests and widget tests should be separated into their own directories.
> > 
> > 
> > @ooms97 Can you elaborate? the test directory is a required standard for the build. Are you saying you would want unit and widget directories under test, and then mirror the structure of lib under both unit and widget directories? I don't mind adding an extra level to do the distinction, if that is what you are asking
> 
> @MrJCipherButtles Yes, that's what I mean. We can mirror the src structure but also add a unit_test and widget_test directory. For example, the class in /lib/model/building.dart would have an associated unit test in /test/unit_test/lib/model/building_test.dart

Currently there is already a widget directory in lib for which I added the widget directory in test. So I don't know if adding an extra directory level would be redundant?

**Comment by ooms97** [comment]
> > > > I think that unit tests and widget tests should be separated into their own directories.
> > > 
> > > 
> > > @ooms97 Can you elaborate? the test directory is a required standard for the build. Are you saying you would want unit and widget directories under test, and then mirror the structure of lib under both unit and widget directories? I don't mind adding an extra level to do the distinction, if that is what you are asking
> > 
> > 
> > @MrJCipherButtles Yes, that's what I mean. We can mirror the src structure but also add a unit_test and widget_test directory. For example, the class in /lib/model/building.dart would have an associated unit test in /test/unit_test/lib/model/building_test.dart
> 
> @ooms97 Currently there is already a widget directory in lib for which I added the widget directory in test. So I don't know if adding an extra directory level would be redundant?

@MrJCipherButtles Can we rename widgetTest to something more conventional for dart, like widget_test instead. Then move all the unit tests into test/unit_test/

**Comment by MrJCipherButtles** [comment]
I'll stop with the quoted replies hehe. What I like about having a simple one-to-one mirror of lib is that it is easy to go to the test folder and see immediately what is currently being tested in lib. Currently, in master, it is not easy to make that quick assessment of what's tested or not. I know the file structure I am proposing is proven to work well with unit testing as a unit test maps to a unit of code (one-to-one). Can we extend this "one-to-one" mapping to widget tests?

**Comment by ooms97** [comment]
This is what I mean by mirroring the lib in unit_test and widget_test:

test/
├── unit_test
│   └── lib
│       ├── model
│       │   ├── building_test.dart
│       │   ├── coordinate_test.dart
│       │   ├── floor_test.dart
│       │   ├── path_test.dart
│       │   └── segment_test.dart
│       └── services
│           └── map_helper_test.dart
└── widget_test
    └── lib
        ├── view
        │   ├── goto_widget_test.dart
        │   └── home_widget_test.dart
        └── widget
            ├── search
            │   └── search_widget_test.dart
            └── sidebar_widget_test.dart

**Comment by MrJCipherButtles** [comment]
Yeah that is what I was envisioning from your explanation. I guess the better solution would be to keep the exact same directory structure under /lib in /test. But to answer your concern of distinguishing between unit and widget test files, we would denote files as:

<filename>_test.dart for unit tests
<filename>_widget_test.dart for widget tests

Is that ideal for you?

**Comment by ooms97** [comment]
Yeah, I'd be happy with that as well :)

**Pull request merged**
